/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente 2023-24
 */
public class CalcolatriceForm extends javax.swing.JFrame {

    /**
     * Creates new form CalcolatriceForm
     */
    public CalcolatriceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbN1 = new javax.swing.JLabel();
        tfN1 = new javax.swing.JTextField();
        tfN2 = new javax.swing.JTextField();
        lbN2 = new javax.swing.JLabel();
        lbRisultatoTitle = new javax.swing.JLabel();
        lbRisultato = new javax.swing.JLabel();
        btnSomma = new javax.swing.JButton();
        btnDifferenza = new javax.swing.JButton();
        btnDivisione = new javax.swing.JButton();
        btnMoltiplicazione = new javax.swing.JButton();
        btnRisultato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcolatrice");

        lbN1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbN1.setForeground(new java.awt.Color(0, 204, 204));
        lbN1.setText("N1");

        tfN1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN1ActionPerformed(evt);
            }
        });

        tfN2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN2ActionPerformed(evt);
            }
        });

        lbN2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbN2.setForeground(new java.awt.Color(0, 204, 204));
        lbN2.setText("N2");

        lbRisultatoTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRisultatoTitle.setForeground(new java.awt.Color(0, 0, 102));
        lbRisultatoTitle.setText("Risultato:");

        lbRisultato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRisultato.setForeground(new java.awt.Color(204, 204, 204));
        lbRisultato.setText(" ");
        lbRisultato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        btnSomma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSomma.setForeground(new java.awt.Color(51, 0, 102));
        btnSomma.setText("+");
        btnSomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSommaActionPerformed(evt);
            }
        });

        btnDifferenza.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDifferenza.setForeground(new java.awt.Color(51, 0, 102));
        btnDifferenza.setText("-");
        btnDifferenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDifferenzaActionPerformed(evt);
            }
        });

        btnDivisione.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDivisione.setForeground(new java.awt.Color(51, 0, 102));
        btnDivisione.setText(":");
        btnDivisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisioneActionPerformed(evt);
            }
        });

        btnMoltiplicazione.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnMoltiplicazione.setForeground(new java.awt.Color(51, 0, 102));
        btnMoltiplicazione.setText("x");
        btnMoltiplicazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoltiplicazioneActionPerformed(evt);
            }
        });

        btnRisultato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRisultato.setForeground(new java.awt.Color(0, 255, 51));
        btnRisultato.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lbN2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfN2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRisultatoTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbRisultato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDifferenza)
                    .addComponent(btnSomma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivisione)
                    .addComponent(btnMoltiplicazione))
                .addGap(44, 44, 44)
                .addComponent(btnRisultato)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbN1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbN2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRisultatoTitle)
                    .addComponent(lbRisultato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSomma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDifferenza))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoltiplicazione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDivisione))
                    .addComponent(btnRisultato, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN1ActionPerformed

    private void tfN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN2ActionPerformed

    private void btnSommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSommaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSommaActionPerformed

    private void btnDifferenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifferenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDifferenzaActionPerformed

    private void btnDivisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivisioneActionPerformed

    private void btnMoltiplicazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoltiplicazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoltiplicazioneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcolatriceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDifferenza;
    private javax.swing.JButton btnDivisione;
    private javax.swing.JButton btnMoltiplicazione;
    private javax.swing.JButton btnRisultato;
    private javax.swing.JButton btnSomma;
    private javax.swing.JLabel lbN1;
    private javax.swing.JLabel lbN2;
    private javax.swing.JLabel lbRisultato;
    private javax.swing.JLabel lbRisultatoTitle;
    private javax.swing.JTextField tfN1;
    private javax.swing.JTextField tfN2;
    // End of variables declaration//GEN-END:variables
}
