
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente 2023-24
 */
public class SediciMaggio extends javax.swing.JFrame {

    /**
     * Creates new form SediciMaggio
     */
    public SediciMaggio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupIntolleranze = new javax.swing.ButtonGroup();
        lbTitolo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCognome = new javax.swing.JLabel();
        tfCognome = new javax.swing.JTextField();
        cbGruppo = new javax.swing.JComboBox<>();
        lbGruppo = new javax.swing.JLabel();
        lbGite = new javax.swing.JLabel();
        checkBoxGitaLova = new javax.swing.JCheckBox();
        checkBoxGitaPiscina = new javax.swing.JCheckBox();
        lbIntolleranze = new javax.swing.JLabel();
        rbIntolleranzeSi = new javax.swing.JRadioButton();
        rbIntolleranzeNo = new javax.swing.JRadioButton();
        btnIscriviti = new javax.swing.JButton();
        lbTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        lbRisultato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Iscrizione Grest");
        setResizable(false);

        lbTitolo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitolo.setForeground(new java.awt.Color(0, 102, 0));
        lbTitolo.setText("Iscriviti al Grest 2024 ViaVai!");

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNome.setText("Nome");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbCognome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCognome.setText("Cognome");

        tfCognome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGruppo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbGruppo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Asilo", "Elementari", "Medie" }));

        lbGruppo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbGruppo.setText("Gruppo");

        lbGite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbGite.setText("Interessato alle seguenti gite:");

        checkBoxGitaLova.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxGitaLova.setText("Lago di Lova");

        checkBoxGitaPiscina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxGitaPiscina.setText("Piscina (Le Vele a Brescia)");

        lbIntolleranze.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbIntolleranze.setText("L'iscritto ha intolleranze alimentari/allergie?");

        btnGroupIntolleranze.add(rbIntolleranzeSi);
        rbIntolleranzeSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbIntolleranzeSi.setText("Si");

        btnGroupIntolleranze.add(rbIntolleranzeNo);
        rbIntolleranzeNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbIntolleranzeNo.setSelected(true);
        rbIntolleranzeNo.setText("No");

        btnIscriviti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIscriviti.setForeground(new java.awt.Color(51, 0, 204));
        btnIscriviti.setText("ISCRIVITI");
        btnIscriviti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIscrivitiActionPerformed(evt);
            }
        });

        lbTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTelefono.setText("Numero di telefono");

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 0));
        btnReset.setText("Reset modulo");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lbRisultato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIscriviti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTitolo)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNome))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbCognome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbGite)
                                .addComponent(checkBoxGitaLova)
                                .addComponent(checkBoxGitaPiscina)
                                .addComponent(lbIntolleranze, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbIntolleranzeSi)
                                    .addGap(50, 50, 50)
                                    .addComponent(rbIntolleranzeNo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbGruppo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbGruppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbTelefono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfTelefono)))
                            .addComponent(lbRisultato))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCognome)
                    .addComponent(tfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGruppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGruppo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefono)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbGite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxGitaLova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxGitaPiscina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbIntolleranze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIntolleranzeSi)
                    .addComponent(rbIntolleranzeNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lbRisultato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addComponent(btnIscriviti))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Utilizzato al click del tasto reset o in seguito
     * all'inserimento avvenuto con successo.
     */
    private void resetDatiInseritiUtente() {
        tfNome.setText("");
        tfCognome.setText("");
        tfTelefono.setText("");
        cbGruppo.setSelectedIndex(0);
        checkBoxGitaLova.setSelected(false);
        checkBoxGitaPiscina.setSelected(false);
        rbIntolleranzeNo.setSelected(true);
    }
    
    private void btnIscrivitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscrivitiActionPerformed
        String nome = tfNome.getText();
        String cognome = tfCognome.getText();
        String gruppo = cbGruppo.getSelectedItem().toString();
        String telefono = tfTelefono.getText();
        
        if (nome.isBlank() || cognome.isBlank() || gruppo.isBlank() || telefono.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Dati inseriti non corretti!", "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
        boolean haIntolleranze = rbIntolleranzeSi.isSelected();
        
        String gite = "";
        if (checkBoxGitaLova.isSelected()) {
            gite += " -Lova";
        }
        if (checkBoxGitaPiscina.isSelected()) {
            gite += " -Piscina";
        }
        
        File f = new File("C:\\Users\\utente 2023-24\\Documents\\NetBeansProjects\\SediciMaggio\\iscrizioni.txt");
        try {
            FileWriter fw = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write("Nome: "+nome+"\n");
            bw.write("Cognome: "+cognome+"\n");
            bw.write("Gruppo: "+gruppo+"\n");
            bw.write("Numero di telefono: "+telefono+"\n");
            bw.write("Gite a cui è interessato:"+gite+"\n");
            if (haIntolleranze) {
                bw.write("Attenzione: HA INTOLLERANZE ALIMENTARI o ALLERGIE!\n");
            }
            bw.write("\n\n");
            
            bw.flush();
            bw.close();

            lbRisultato.setText("Iscrizione avvenuta con successo!");
            lbRisultato.setForeground(Color.green);
            
            resetDatiInseritiUtente();
        } catch (IOException ex) {
            Logger.getLogger(SediciMaggio.class.getName()).log(Level.SEVERE, null, ex);
            
            JOptionPane.showMessageDialog(rootPane, "Si è verificato un problema. Andare alla segreteria dell'oratorio per effettuare l'iscrizione", "Errore", JOptionPane.ERROR_MESSAGE);
            
            lbRisultato.setText("Errore nell'aggiunta dell'iscrizione.");
            lbRisultato.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnIscrivitiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lbRisultato.setText("");
        resetDatiInseritiUtente();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SediciMaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SediciMaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SediciMaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SediciMaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SediciMaggio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupIntolleranze;
    private javax.swing.JButton btnIscriviti;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbGruppo;
    private javax.swing.JCheckBox checkBoxGitaLova;
    private javax.swing.JCheckBox checkBoxGitaPiscina;
    private javax.swing.JLabel lbCognome;
    private javax.swing.JLabel lbGite;
    private javax.swing.JLabel lbGruppo;
    private javax.swing.JLabel lbIntolleranze;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRisultato;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitolo;
    private javax.swing.JRadioButton rbIntolleranzeNo;
    private javax.swing.JRadioButton rbIntolleranzeSi;
    private javax.swing.JTextField tfCognome;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
