/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente 2023-24
 */
public class Vivaio extends javax.swing.JFrame {

    /**
     * Creates new form Vivaio
     */
    public Vivaio() {
        initComponents();
    }
    
    Albero a = new Albero();
    
    private void setValoriAlbero() {
        a.setNome(tfNome.getText());
        a.setQta(Integer.parseInt(tfQta.getText()));
        a.setPrezzo(Float.parseFloat(tfPrezzo.getText()));
        a.setSpecie(tfSpecie.getText());
    }
    
    private void resetInserimento() {
        lbCosto.setText("");
        tfNome.setText("");
        tfQta.setText("");
        tfPrezzo.setText("");
        tfSpecie.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitolo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbQta = new javax.swing.JLabel();
        tfQta = new javax.swing.JTextField();
        lbPrezzo = new javax.swing.JLabel();
        tfPrezzo = new javax.swing.JTextField();
        tfSpecie = new javax.swing.JTextField();
        lbSpecie = new javax.swing.JLabel();
        btCosto = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        lbCosto = new javax.swing.JLabel();
        taLogsPane = new javax.swing.JScrollPane();
        taLogs = new javax.swing.JTextArea();
        btInserisci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitolo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitolo.setText("GESTISCI IL VIVAIO");

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNome.setText("Nome:");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbQta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbQta.setText("Quantità:");

        tfQta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbPrezzo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPrezzo.setText("Prezzo:");

        tfPrezzo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfSpecie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbSpecie.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSpecie.setText("Specie:");

        btCosto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCosto.setText("Trova il costo");
        btCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCostoActionPerformed(evt);
            }
        });

        btReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btReset.setText("Reset inserimenti");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        lbCosto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCosto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCosto.setText(" ");

        taLogs.setEditable(false);
        taLogs.setColumns(20);
        taLogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taLogs.setRows(5);
        taLogsPane.setViewportView(taLogs);

        btInserisci.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btInserisci.setText("Inserisci nel DB");
        btInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserisciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ultimi alberi registrati:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbPrezzo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfPrezzo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbQta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCosto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btInserisci)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSpecie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taLogsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btReset)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitolo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQta)
                            .addComponent(tfQta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrezzo)
                            .addComponent(tfPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSpecie)
                            .addComponent(tfSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taLogsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btInserisci, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCostoActionPerformed
        setValoriAlbero();
        lbCosto.setText(a.costo()+"€");
    }//GEN-LAST:event_btCostoActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        resetInserimento();
        //Quando viene premuto tasto reset, svuota anche i logs degli ultimi inserimenti
        taLogs.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    private void btInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserisciActionPerformed
        setValoriAlbero(); //Se viene premuto senza premere prima "Costo"
        taLogs.append(a.toString()+'\n');
        //Appena un albero viene salvato, aggiungi alla TextArea degli ultimi inserimenti
        resetInserimento();
    }//GEN-LAST:event_btInserisciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vivaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vivaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vivaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vivaio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vivaio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCosto;
    private javax.swing.JButton btInserisci;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPrezzo;
    private javax.swing.JLabel lbQta;
    private javax.swing.JLabel lbSpecie;
    private javax.swing.JLabel lbTitolo;
    private javax.swing.JTextArea taLogs;
    private javax.swing.JScrollPane taLogsPane;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPrezzo;
    private javax.swing.JTextField tfQta;
    private javax.swing.JTextField tfSpecie;
    // End of variables declaration//GEN-END:variables
}
