
import java.awt.Color;
import java.awt.List;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente 2023-24
 */
public class JFIscrizione extends javax.swing.JFrame {

    /**
     * Creates new form JFIscrizione
     */
    public JFIscrizione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipo = new javax.swing.ButtonGroup();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCognome = new javax.swing.JTextField();
        lbCognome = new javax.swing.JLabel();
        lbTipologia = new javax.swing.JLabel();
        rbStudente = new javax.swing.JRadioButton();
        rbProfessore = new javax.swing.JRadioButton();
        rbATA = new javax.swing.JRadioButton();
        cbArgomento = new javax.swing.JComboBox<>();
        lbArgomento = new javax.swing.JLabel();
        lbModalita = new javax.swing.JLabel();
        checkPresenza = new javax.swing.JCheckBox();
        checkOnline = new javax.swing.JCheckBox();
        btnIscriviti = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lbRisultato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNome.setText("NOME");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfCognome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbCognome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCognome.setText("COGNOME");

        lbTipologia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTipologia.setText("TIPOLOGIA");

        groupTipo.add(rbStudente);
        rbStudente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbStudente.setText("Studente");

        groupTipo.add(rbProfessore);
        rbProfessore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbProfessore.setText("Professore");

        groupTipo.add(rbATA);
        rbATA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbATA.setText("Personale ATA");

        cbArgomento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbArgomento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Informatica", "Matematica", "Giochi matematici", "Certificazione Inglese", "Certificazione Spagnolo", "Certificazione Tedesco", "Filosofia" }));
        cbArgomento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbArgomentoActionPerformed(evt);
            }
        });

        lbArgomento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbArgomento.setText("ARGOMENTO");

        lbModalita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbModalita.setText("MODALITÀ");

        checkPresenza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkPresenza.setText("Presenza");

        checkOnline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkOnline.setText("Online");

        btnIscriviti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIscriviti.setText("Iscriviti");
        btnIscriviti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIscrivitiActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lbRisultato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRisultato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRisultato.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRisultato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIscriviti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfNome))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbCognome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbTipologia)
                            .addComponent(rbStudente)
                            .addComponent(rbProfessore)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbArgomento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbArgomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbATA)
                            .addComponent(lbModalita)
                            .addComponent(checkPresenza, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCognome)
                    .addComponent(tfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTipologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbStudente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbProfessore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbATA)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbArgomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbArgomento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbModalita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPresenza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOnline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIscriviti)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbRisultato)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIscrivitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscrivitiActionPerformed
        File f = new File("C:\\Users\\utente 2023-24\\Documents\\iscrizioni_modulo.txt");
        try {
            FileWriter fw = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write("Nome: "+tfNome.getText()+"\n");
            bw.write("Cognome: "+tfCognome.getText()+"\n");
            
            String tipologia = "";
            if (rbStudente.isSelected()) tipologia = "studente";
            if (rbProfessore.isSelected()) tipologia = "professore";
            if (rbATA.isSelected()) tipologia = "personale ATA";
            bw.write("Tipologia: "+tipologia+"\n");
            
            bw.write("Argomento: "+cbArgomento.getSelectedItem()+"\n");
            
            String mod;
            if (checkPresenza.isSelected() && !checkOnline.isSelected()) {
                mod = "in presenza";
            } else if (!checkPresenza.isSelected() && checkOnline.isSelected()) {
                mod = "a distanza";
            } else {
                mod = "sia in presenza che a distanza";
            }
            bw.write("Modalità: "+mod+"\n\n\n");
            
            bw.flush();
            bw.close();
            
            lbRisultato.setForeground(Color.black);
            lbRisultato.setBackground(Color.green);
            lbRisultato.setText("Registrazione avvenuta con successo.");
        } catch (IOException ex) {
            Logger.getLogger(JFIscrizione.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Scrittura file non completata con successo.", "Errore", JOptionPane.ERROR_MESSAGE);
            lbRisultato.setForeground(Color.white);
            lbRisultato.setBackground(Color.red);
            lbRisultato.setText("Errore nell'invio dei dati.");
        }
    }//GEN-LAST:event_btnIscrivitiActionPerformed

    private void cbArgomentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbArgomentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbArgomentoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cbArgomento.setSelectedIndex(0);
        checkOnline.setSelected(false);
        checkPresenza.setSelected(false);
        rbATA.setSelected(false);
        rbProfessore.setSelected(false);
        rbStudente.setSelected(false);
        tfCognome.setText("");
        tfNome.setText("");
        lbRisultato.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFIscrizione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFIscrizione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFIscrizione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFIscrizione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFIscrizione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIscriviti;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbArgomento;
    private javax.swing.JCheckBox checkOnline;
    private javax.swing.JCheckBox checkPresenza;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JLabel lbArgomento;
    private javax.swing.JLabel lbCognome;
    private javax.swing.JLabel lbModalita;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRisultato;
    private javax.swing.JLabel lbTipologia;
    private javax.swing.JRadioButton rbATA;
    private javax.swing.JRadioButton rbProfessore;
    private javax.swing.JRadioButton rbStudente;
    private javax.swing.JTextField tfCognome;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
