/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente 2023-24
 */
public class Inizio extends javax.swing.JFrame {

    /**
     * Creates new form Inizio
     */
    public Inizio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInizio = new javax.swing.JLabel();
        btnTriangolo = new javax.swing.JButton();
        btnQuadrato = new javax.swing.JButton();
        btnRettangolo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbInizio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbInizio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInizio.setText("Forma geometrica");

        btnTriangolo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTriangolo.setText("Triangolo");
        btnTriangolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangoloActionPerformed(evt);
            }
        });

        btnQuadrato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQuadrato.setText("Quadrato");
        btnQuadrato.setActionCommand("Quadrato");
        btnQuadrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadratoActionPerformed(evt);
            }
        });

        btnRettangolo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRettangolo.setText("Rettangolo");
        btnRettangolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRettangoloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbInizio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTriangolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuadrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRettangolo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbInizio)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTriangolo)
                    .addComponent(btnQuadrato)
                    .addComponent(btnRettangolo))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTriangoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangoloActionPerformed
        jfTriangolo t = new jfTriangolo();
        t.setVisible(true);
        jfQuadrato q = new jfQuadrato();
        q.dispose();
        jfRettangolo r = new jfRettangolo();
        r.dispose();
    }//GEN-LAST:event_btnTriangoloActionPerformed

    private void btnQuadratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadratoActionPerformed
        jfTriangolo t = new jfTriangolo();
        t.dispose();
        jfQuadrato q = new jfQuadrato();
        q.setVisible(true);
        jfRettangolo r = new jfRettangolo();
        r.dispose();
    }//GEN-LAST:event_btnQuadratoActionPerformed

    private void btnRettangoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRettangoloActionPerformed
        jfTriangolo t = new jfTriangolo();
        t.dispose();
        jfQuadrato q = new jfQuadrato();
        q.dispose();
        jfRettangolo r = new jfRettangolo();
        r.setVisible(true);
    }//GEN-LAST:event_btnRettangoloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inizio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuadrato;
    private javax.swing.JButton btnRettangolo;
    private javax.swing.JButton btnTriangolo;
    private javax.swing.JLabel lbInizio;
    // End of variables declaration//GEN-END:variables
}
